/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;
import net.objecthunter.exp4j.Expression;
import net.objecthunter.exp4j.ExpressionBuilder;
/**
 *
 * @author ASUS
 */
public class Calculator extends javax.swing.JFrame {
    
//    double Num_1;
//    double Num_2;
//    String operator;
//    Double result;
    String text_1;
    String text_2;
    

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        setTitle("Simple Calculator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Result = new javax.swing.JPanel();
        Display = new javax.swing.JLabel();
        Buttons = new javax.swing.JPanel();
        N0_1 = new javax.swing.JButton();
        N0_2 = new javax.swing.JButton();
        N0_3 = new javax.swing.JButton();
        N0_4 = new javax.swing.JButton();
        N0_5 = new javax.swing.JButton();
        N0_6 = new javax.swing.JButton();
        N0_7 = new javax.swing.JButton();
        N0_8 = new javax.swing.JButton();
        N0_9 = new javax.swing.JButton();
        N0_10 = new javax.swing.JButton();
        N0_11 = new javax.swing.JButton();
        N0_12 = new javax.swing.JButton();
        N0_13 = new javax.swing.JButton();
        N0_14 = new javax.swing.JButton();
        N0_15 = new javax.swing.JButton();
        N0_16 = new javax.swing.JButton();
        N0_17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Result.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ResultLayout = new javax.swing.GroupLayout(Result);
        Result.setLayout(ResultLayout);
        ResultLayout.setHorizontalGroup(
            ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        ResultLayout.setVerticalGroup(
            ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Buttons.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        N0_1.setText("1");
        N0_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_1ActionPerformed(evt);
            }
        });

        N0_2.setText("2");
        N0_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_2ActionPerformed(evt);
            }
        });

        N0_3.setText("3");
        N0_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_3ActionPerformed(evt);
            }
        });

        N0_4.setText("4");
        N0_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_4ActionPerformed(evt);
            }
        });

        N0_5.setText("5");
        N0_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_5ActionPerformed(evt);
            }
        });

        N0_6.setText("6");
        N0_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_6ActionPerformed(evt);
            }
        });

        N0_7.setText("7");
        N0_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_7ActionPerformed(evt);
            }
        });

        N0_8.setText("8");
        N0_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_8ActionPerformed(evt);
            }
        });

        N0_9.setText("9");
        N0_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_9ActionPerformed(evt);
            }
        });

        N0_10.setText("+");
        N0_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_10ActionPerformed(evt);
            }
        });

        N0_11.setText("/");
        N0_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_11ActionPerformed(evt);
            }
        });

        N0_12.setText("-");
        N0_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_12ActionPerformed(evt);
            }
        });

        N0_13.setText("0");
        N0_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_13ActionPerformed(evt);
            }
        });

        N0_14.setText(".");
        N0_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_14ActionPerformed(evt);
            }
        });

        N0_15.setText("=");
        N0_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_15ActionPerformed(evt);
            }
        });

        N0_16.setText("*");
        N0_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_16ActionPerformed(evt);
            }
        });

        N0_17.setText("Clear");
        N0_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N0_17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsLayout = new javax.swing.GroupLayout(Buttons);
        Buttons.setLayout(ButtonsLayout);
        ButtonsLayout.setHorizontalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addComponent(N0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N0_2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N0_3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N0_10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addComponent(N0_4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N0_5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N0_6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(N0_12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonsLayout.createSequentialGroup()
                        .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(N0_7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(N0_13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ButtonsLayout.createSequentialGroup()
                                .addComponent(N0_8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N0_9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N0_11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ButtonsLayout.createSequentialGroup()
                                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(N0_17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(ButtonsLayout.createSequentialGroup()
                                        .addComponent(N0_14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(N0_15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N0_16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonsLayout.setVerticalGroup(
            ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N0_1)
                    .addComponent(N0_2)
                    .addComponent(N0_3)
                    .addComponent(N0_10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N0_5)
                    .addComponent(N0_4)
                    .addComponent(N0_6)
                    .addComponent(N0_12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N0_9)
                    .addComponent(N0_7)
                    .addComponent(N0_8)
                    .addComponent(N0_11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N0_15)
                    .addComponent(N0_14)
                    .addComponent(N0_13)
                    .addComponent(N0_16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(N0_17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void N0_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_1ActionPerformed
        Display.setText(Display.getText() + "1");
    }//GEN-LAST:event_N0_1ActionPerformed

    private void N0_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_2ActionPerformed
        Display.setText(Display.getText() + "2");
    }//GEN-LAST:event_N0_2ActionPerformed

    private void N0_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_3ActionPerformed
        Display.setText(Display.getText() + "3");
    }//GEN-LAST:event_N0_3ActionPerformed

    private void N0_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_4ActionPerformed
        Display.setText(Display.getText() + "4");
    }//GEN-LAST:event_N0_4ActionPerformed

    private void N0_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_5ActionPerformed
        Display.setText(Display.getText() + "5");
    }//GEN-LAST:event_N0_5ActionPerformed

    private void N0_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_6ActionPerformed
        Display.setText(Display.getText() + "6");
    }//GEN-LAST:event_N0_6ActionPerformed

    private void N0_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_7ActionPerformed
        Display.setText(Display.getText() + "7");
    }//GEN-LAST:event_N0_7ActionPerformed

    private void N0_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_8ActionPerformed
        Display.setText(Display.getText() + "8");
    }//GEN-LAST:event_N0_8ActionPerformed

    private void N0_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_9ActionPerformed
        Display.setText(Display.getText() + "9");
    }//GEN-LAST:event_N0_9ActionPerformed

    private void N0_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_10ActionPerformed
//        Num_1 = Double.parseDouble(Display.getText());
//        operator = "+";
//        Display.setText(Display.getText() + "+");  // +
        text_1 = Display.getText();
        Display.setText(Display.getText() + "+");
    }//GEN-LAST:event_N0_10ActionPerformed

    private void N0_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_11ActionPerformed
//        Num_1 = Double.parseDouble(Display.getText());
//        operator = "/";
//        Display.setText(Display.getText() + "/");   // /
        text_1 = Display.getText();
        Display.setText(Display.getText() + "/");
    }//GEN-LAST:event_N0_11ActionPerformed

    private void N0_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_12ActionPerformed
//        Num_1 = Double.parseDouble(Display.getText());
//        operator = "-";        
//        Display.setText(Display.getText() + "-");   // -
        text_1 = Display.getText();
        Display.setText(Display.getText() + "-");
    }//GEN-LAST:event_N0_12ActionPerformed

    private void N0_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_13ActionPerformed
        Display.setText(Display.getText() + "0");   // zero
    }//GEN-LAST:event_N0_13ActionPerformed

    private void N0_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_14ActionPerformed
        Display.setText(Display.getText() + ".");          // .
    }//GEN-LAST:event_N0_14ActionPerformed

    private void N0_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_15ActionPerformed
//        String fullText = Display.getText();            // =
//        String[] parts = fullText.split("\\"+operator);
//        
//        if(parts.length==2){
//            Num_2 = Double.parseDouble(parts[1]);
//            result = 0.0;
//            
//            switch(operator){
//                case "+":
//                    result = Num_1 + Num_2 ;
//                    break;
//                case "-":
//                    result = Num_1 - Num_2 ;
//                    break;
//                case "/":
//                    result = Num_1 / Num_2 ;
//                    break;
//                case "*":
//                    result = Num_1 * Num_2 ;
//                    break;                    
//            }
//            
//        Display.setText(Display.getText() + " = " + result);
//        }
        String expression = Display.getText(); 

        // Check if expression ends with an operator (invalid)
        if (expression.endsWith("+") || expression.endsWith("-") ||
            expression.endsWith("*") || expression.endsWith("/")) {
            Display.setText("Invalid Expression!");
            return;
        }

        // Remove previous result if "=" exists
        if (expression.contains("=")) {
            expression = expression.substring(0, expression.indexOf("=")).trim();
        }

        try {
            // Evaluate the expression using exp4j
            Expression exp = new ExpressionBuilder(expression).build();
            double result = exp.evaluate();

            // Display the result
//            Display.setText(expression + " = " + result);
            Display.setText(Double.toString(result));
        } catch (ArithmeticException e) {
            Display.setText("Math Error: " + e.getMessage());
        } catch (IllegalArgumentException e) {
            Display.setText("Invalid Input!");
        } catch (Exception e) {
            Display.setText("Error in Calculation!");
        }           
        
    }//GEN-LAST:event_N0_15ActionPerformed

    private void N0_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_16ActionPerformed
//        Num_1 = Double.parseDouble(Display.getText());
//        operator = "*";        
//        Display.setText(Display.getText() + "*");        // *
        text_1 = Display.getText();
        Display.setText(Display.getText() + "*");
    }//GEN-LAST:event_N0_16ActionPerformed

    private void N0_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N0_17ActionPerformed
        Display.setText("");
    }//GEN-LAST:event_N0_17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttons;
    private javax.swing.JLabel Display;
    private javax.swing.JButton N0_1;
    private javax.swing.JButton N0_10;
    private javax.swing.JButton N0_11;
    private javax.swing.JButton N0_12;
    private javax.swing.JButton N0_13;
    private javax.swing.JButton N0_14;
    private javax.swing.JButton N0_15;
    private javax.swing.JButton N0_16;
    private javax.swing.JButton N0_17;
    private javax.swing.JButton N0_2;
    private javax.swing.JButton N0_3;
    private javax.swing.JButton N0_4;
    private javax.swing.JButton N0_5;
    private javax.swing.JButton N0_6;
    private javax.swing.JButton N0_7;
    private javax.swing.JButton N0_8;
    private javax.swing.JButton N0_9;
    private javax.swing.JPanel Result;
    // End of variables declaration//GEN-END:variables
}
